name: Run Dagger Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dagger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install DVC
        run: pip install "dvc[ssh]"

      - name: Override DVC remote to HTTPS for CI
        run: dvc remote modify storage url https://github.com/patrinita/itu-sdse-data-storage.git

      - name: Pull DVC data
        run: dvc pull

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: dagger/go.mod
          cache-dependency-path: dagger/go.sum

      - name: Set up Dagger
        uses: dagger/dagger-for-github@v7
        with:
          version: "0.19.8"

      - name: Run Dagger Pipeline
        run: |
          cd dagger
          go mod download
          dagger run go run pipeline.go

      - name: Prepare model for validator
        run: |
          mkdir -p model
          cp cookie_eaters/artifacts/lead_model_lr.pkl model/model.pkl
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model/model.pkl

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
